### ISSUE TITLE
Issues with Boost 1.55

### ISSUE THREAD

**Issue by colincsl** [jbohren/conman#16]
I had to change a Boost include in Scheme.cpp (https://github.com/jbohren/conman/blob/master/conman/src/scheme.cpp) 

From:
```c++
#include <boost/property/function_property_map.hpp>
```
To:
```c++
#include <boost/property_map/function_property_map.hpp>
```
I'm not sure how this affects previous version of Boost.

**Comment by jbohren** [comment]
Fixed by #19
