### ISSUE TITLE
optimization: change all `std::map`s to `boost::unordered_map`s

### ISSUE THREAD

**Issue by jbohren** [jbohren/conman#22]
http://www.boost.org/doc/libs/1_48_0/doc/html/boost/unordered_map.html

@RoseWall Can you look into this and prepare a PR?

**Comment by konradb3** [comment]
I would also consider using C++11 std::unordered_map when avalible.

**Comment by jbohren** [comment]
A global `conman::HashMap` typedef would be good.

**Comment by jbohren** [comment]
Performed by #26
